name = "rust"
entrypoint = "main.rs"
extensions = [
  "rs"
]
packages = [
  # "rust-gdb"
]
setup = [
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable",
  "mkdir $HOME/.profile.d && echo 'source $HOME/.cargo/env' | tee $HOME/.profile.d/cargo",
]

[compile]
command = [
  "rustc",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "fn main() {\n  println!(\"hello\");\n}"
  output = "hello\n"
